export enum CbiQuestionOptionTypeEnum {
  SINGLE_CHOICE = 1,
  MULTI_CHOICE = 2,
  ENTER_ANSWER = 3,
  UPLOAD_FILE = 4,
}

export const MIN_NUMBER_ANSWER_SINGLE_CHOICE_TYPE = 2;
export const MAX_NUMBER_ANSWER_SINGLE_CHOICE_TYPE = 10;
export const MIN_NUMBER_ANSWER_MULTI_CHOICE_TYPE = 3;
export const MAX_NUMBER_ANSWER_MULTI_CHOICE_TYPE = 10;
