// DECLARE QUERY KEY FOR REACT QUERY
export const QUERY_KEY = Object.freeze({
  HELLO_WORLD: "HELLO_WORLD",
  USER_LIST: "USER_LIST",
  TOPIC_LIST: "TOPIC_LIST",
  LEVEL_LIST: "LEVEL_LIST",
  PODCAST_LIST: "PODCAST_LIST",
  VIDEO_LIST: "VIDEO_LIST",
  VIDEO: "VIDEO",
  GET_TRANSCRIPT_VIDEO: "GET_TRANSCRIPT_VIDEO",
});
