import { Article } from "@/src/common/interfaces/common.interface";
import { PICTURE } from "./../../common/constants/common.constant";
export const DATA_ARTICLE: Article[] = [
  {
    id: 1,
    lang: "vi",
    category: {
      type: "POLICY",
      id: 1,
      name: "cate",
      slug: "cate",
    },
    thumbnail: {
      id: 1,
      key: "string",
      type: "png",
      url: PICTURE("1"),
    },
    field: "WOOD",
    createdAt: "12/05/2022",
    updatedAt: "12/05/2022",
    deletedAt: "12/05/2022",
    version: 1,
    isFeature: 1,
    title:
      "IFC hỗ trợ Việt Nam chuyển đổi sang mô hình tăng trưởng kinh tế carbon thấp",
    shortDesc:
      "Với việc ký kết 2 biên bản ghi nhớ hợp tác với Bộ Tài nguyên và Môi trường và Ngân hàng Nhà nước Việt Nam, IFC sẽ hỗ trợ thúc đẩy đổi mới sáng tạo và tài chính của khu vực kinh tế tư nhân đối với quá trình chuyển đổi sang nền kinh tế xanh, bền vững, và phát thải carbon thấp…",
    content: "content",
    author: "VTV",
    slug: "ifc-ho-tro-viet-nam",
  },
  {
    id: 2,
    lang: "vi",
    category: {
      id: 2,
      type: "POLICY",
      name: "cate",
      slug: "cate",
    },
    thumbnail: {
      id: 2,
      key: "string",
      type: "png",
      url: PICTURE("2"),
    },
    field: "WOOD",
    createdAt: "12/05/2022",
    updatedAt: "12/05/2022",
    deletedAt: "12/05/2022",
    version: 1,
    isFeature: 1,
    title: "28/6: Tập huấn giảm khí nhà kính và cơ chế carbon",
    shortDesc:
      "Cục Phát triển doanh nghiệp (Bộ Kế hoạch và Đầu tư) tổ chức chương trình tập huấn “Tổng quan về yêu cầu giảm khí nhà kính và cơ chế carbon-Thách thức và giải pháp ban đầu cho doanh nghiệp”.",
    content: "content",
    author: "VTV",
    slug: "tap-huan-giam-khi-nha-kinh",
  },
  {
    id: 3,
    lang: "vi",
    category: {
      id: 3,
      type: "POLICY",
      name: "cate",
      slug: "cate",
    },
    thumbnail: {
      id: 3,
      key: "string",
      type: "png",
      url: PICTURE("3"),
    },
    field: "WOOD",
    createdAt: "12/05/2022",
    updatedAt: "12/05/2022",
    deletedAt: "12/05/2022",
    version: 1,
    isFeature: 1,
    title:
      "USAID assists Vietnamese businesses to reduce greenhouse gas emission",
    shortDesc:
      "NDO/VNA - The United States Agency for International Development (USAID), in coordination with the Enterprise Development Agency under the Ministry of Planning and Investment, organised a training workshop in Ho Chi Minh City on June 29, aiming to provide information relating to greenhouse gas reduction as well as offering solutions to businesses.",
    content: "content",
    author: "VTV",
    slug: "vietname-businesses-to-reduce-energy",
  },
  {
    id: 4,
    lang: "vi",
    category: {
      id: 4,
      type: "POLICY",
      name: "cate",
      slug: "cate",
    },
    thumbnail: {
      id: 4,
      key: "string",
      type: "png",
      url: PICTURE("4"),
    },
    field: "WOOD",
    createdAt: "12/05/2022",
    updatedAt: "12/05/2022",
    deletedAt: "12/05/2022",
    version: 1,
    isFeature: 1,
    title:
      "USAID assists Vietnamese businesses to reduce greenhouse gas emission",
    shortDesc:
      "NDO/VNA - The United States Agency for International Development (USAID), in coordination with the Enterprise Development Agency under the Ministry of Planning and Investment, organised a training workshop in Ho Chi Minh City on June 29, aiming to provide information relating to greenhouse gas reduction as well as offering solutions to businesses.",
    content: "content",
    author: "VTV",
    slug: "assists-Vietnamese-businesses-to",
  },
  {
    id: 5,
    lang: "vi",
    category: {
      id: 5,
      type: "POLICY",
      name: "cate",
      slug: "cate",
    },
    thumbnail: {
      id: 5,
      key: "string",
      type: "png",
      url: PICTURE("5"),
    },
    field: "WOOD",
    createdAt: "12/05/2022",
    updatedAt: "12/05/2022",
    deletedAt: "12/05/2022",
    version: 1,
    isFeature: 1,
    title: "28/6: Tập huấn giảm khí nhà kính và cơ chế carbon",
    shortDesc:
      "Cục Phát triển doanh nghiệp (Bộ Kế hoạch và Đầu tư) tổ chức chương trình tập huấn “Tổng quan về yêu cầu giảm khí nhà kính và cơ chế carbon-Thách thức và giải pháp ban đầu cho doanh nghiệp”.",
    content: "content",
    author: "VTV",
    slug: "co-che-carbon",
  },
  {
    id: 6,
    lang: "vi",
    category: {
      id: 6,
      type: "POLICY",
      name: "cate",
      slug: "cate",
    },
    thumbnail: {
      id: 6,
      key: "string",
      type: "png",
      url: PICTURE("6"),
    },
    field: "WOOD",
    createdAt: "12/05/2022",
    updatedAt: "12/05/2022",
    deletedAt: "12/05/2022",
    version: 1,
    isFeature: 1,
    title:
      "IFC hỗ trợ Việt Nam chuyển đổi sang mô hình tăng trưởng kinh tế carbon thấp",
    shortDesc:
      "Với việc ký kết 2 biên bản ghi nhớ hợp tác với Bộ Tài nguyên và Môi trường và Ngân hàng Nhà nước Việt Nam, IFC sẽ hỗ trợ thúc đẩy đổi mới sáng tạo và tài chính của khu vực kinh tế tư nhân đối với quá trình chuyển đổi sang nền kinh tế xanh, bền vững, và phát thải carbon thấp…",
    content: "content",
    author: "VTV",
    slug: "kinh-te-carbon-thap",
  },
];
