export const QUERY_KEYS = Object.freeze({
  CATEGORY_LIST_POLICY: 'CATEGORY_LIST_POLICY',
  CATEGORY_LIST_ENTERPRISE: 'CATEGORY_LIST_ENTERPRISE',
  CATEGORY_LIST: 'CATEGORY_LIST',
  CATEGORY_DETAIL: 'CATEGORY_DETAIL',
  ARTICLE_LIST: 'ARTICLE_LIST',
  ARTICLE_LIST_ENTERPRISE: 'ARTICLE_LIST_ENTERPRISE',
  EVENT_LIST: 'EVENT_LIST',
  EVENT_DETAIL: 'EVENT_DETAIL',
  REGISTER_EVENT: 'REGISTER_EVENT',
  DOCUMENT_LIST: 'DOCUMENT_LIST',
  ADMIN_ACCOUNT_LIST:'ADMIN_ACCOUNT_LIST',
  ADD_NEW_ACCOUNT: 'ADD_NEW_ACCOUNT',
  ADMIN_ACCOUNT_DETAIL: 'ADMIN_ACCOUNT_DETAIL',
  AUTHORIZATION_LIST: 'AUTHORIZATION_LIST',
  AUTH :'AUTH'
});
