export const LangStrings = {
  vi: {
    storeSystem: "Hệ thống cửa hàng",
    language: "Ngôn ngữ",
    customerSupport: "Hỗ trợ khách hàng",
    signUp: "Đăng ký",
    logIn: "Đăng nhập",
    logOut: "Đăng xuất",
    findPlaceholder: "Nhập tên sản phẩm",
    find: "Tìm",
    noProducts: "Chưa có sản phẩm nào",
    subcriptionRegister: "Đăng ký nhận tin",
    subcriptionRegisterText: "Nhập email của bạn",
    subcriptionRegisterBtn: "ĐĂNG KÝ",
    emailIsRequired: "Email được yêu cầu",
    emailIsInvalid: "Email không hợp lệ",
    successSubscription: "Đăng kí thành công",
    failSubscription: "Đăng kí thất bại. Vui lòng thử lại",
    existedEmail: "Email đã được đăng kí",
    address: "Địa chỉ",
    email: "Email",
    hotline: "Hotline",
    aboutCompany: "Về công ty",
    aboutLT: "Về Long Thành",
    product: "Sản phẩm",
    FAQ: "Câu hỏi thường gặp",
    policy: "Thông tin chính sách",
    directLinks: "Liên kết nhanh",
    representativeOffice: "Văn phòng đại diện",
    payment: "Thanh toán",
    follow: "Theo dõi",
    certification: "Chứng nhận",
    followOnFacebook: "Kết nối Facebook",
    followOnShopee: "Kết nối Shopee",
    followOnZalo: "Kết nối Zalo",
    homePage: "Trang chủ",
    relatedProducts: "Sản phẩm liên quan",
    viewAll: "Xem tất cả",
    allComboBelongsTo: "Tất cả Combo thuộc sản phẩm",
    sortBy: "Sắp xếp theo",
    priceContact: "Giá thành",
    sorryCombo: "Rất tiếc, không tìm thấy combo nào.",
    productReview: "Đánh giá sản phẩm",
    postedAt: "Đã đăng",
    detailDescription: "Mô tả chi tiết",
    viewMore: "Xem thêm",
    viewLess: "Thu gọn",
    feature: "NỔI BẬT",
    discount: "Giảm giá",
    expireOn: "hết hạn sau",
    donate: "Quyên góp",
    callOn: "Kêu gọi",
    status: "Tình trạng",
    inStock: "Còn hàng",
    outOfStock: "Hết hàng",
    addToCart: "Thêm vào giỏ hàng",
    buy: "Mua hàng",
    share: "Chia sẻ",
    code: "Mã sản phẩm",
    contactLongThanh: "Liên hệ",
    chooseContactMethod: "Chọn phương thức liên hệ",
    review: "đánh giá",
    sold: "Đã bán",
    favourite: "Yêu thích",
    confirmEmail: "XÁC NHẬN EMAIL",
    confirmEmailLowercase: "Xác nhận email",
    codeSent: "Mã xác minh đã được gửi đến địa chỉ",
    pleaseConfirm: "Vui lòng xác nhận.",
    validateEmail: "Xác thực Email",
    agree: "Đã hiểu",
    createAccount: "Tạo tài khoản",
    alreadyHaveAccount: "Bạn đã có tài khoản?",
    fullName: "Họ và tên",
    fullNameRequired: "Họ tên được yêu cầu",
    fullNameExceed: "Họ và tên có 2 từ trở lên",
    phoneNum: "Số điện thoại",
    phoneIsRequired: "Số điện thoại được yêu cầu",
    phoneIsInvalid: "Số điện thoại không hợp lệ",
    password: "Mật khẩu",
    passwordIsRequired: "Mật khẩu được yêu cầu",
    passwordNotMatch: "Mật khẩu không khớp",
    confirmPassword: "Xác nhận lại mật khẩu",
    byRegister: "Bằng việc Đăng ký, bạn đã đồng ý với Long Thành Plastic về",
    termCondition: "Điều khoản dịch vụ",
    privacyPolicy: "Chính sách bảo mật",
    orLoginWith: "hoặc đăng nhập bằng",
    dontHaveAccount: "Bạn chưa có tài khoản?",
    saveAccount: "Lưu tài khoản",
    forgotPassword: "Quên mật khẩu?",
    recoverPassword: "Vui lòng nhập email để khôi phục mật khẩu",
    pleaseEnterEmail: "Vui lòng nhập email",
    buyNow: "Mua ngay",
    nowOnlyHas: "hiện chỉ còn",
    items: "sản phẩm",
    followLatestEmail: "Theo dõi Bản tin mới nhất qua Email",
    yearAgo: "năm trước",
    monthAgo: "tháng trước",
    dayAgo: "ngày trước",
    hourAgo: "giờ trước",
    minAgo: "phút trước",
    news: "Tin Mới",
    relatedPosts: "Tin Liên quan",
    updatedSuccessfully: "Cập nhật thành công",
    logInAgain: "Tạo mật khẩu thành công. Vui lòng đăng nhập vào tài khoản bằng mật khẩu mới.",
    logInNow: "Đăng nhập ngay",
    createNewPassword: "Tạo mật khẩu mới",
    enterNewPassword: "Nhập mật khẩu mới",
    pleaseEnterPassword: "Vui lòng nhập mật khẩu",
    confirmNewPassword: "Xác nhận mật khẩu mới",
    confirmNewPasswordNotMatch: "Xác nhận mật khẩu phải giống với mật khẩu",
    changePassword: "Đổi mật khẩu",
    orderFail: "Đặt hàng không thành công",
    orderInfoChanged: "Thông tin trong giỏ hàng đã có sự thay đổi",
    backCart: "Trở về giỏ hàng",
    shippingInfo: "Thông tin giao hàng",
    contactLater: "Liên hệ sau",
    paymentMethod: "Hình thức thanh toán",
    prevPage: "Trang trước",
    next: "Tiếp theo",
    edit: "Chỉnh sửa",
    change: "Thay đổi",
    newAddress: "Thêm địa chỉ",
    newShippingAddress: "Thêm địa chỉ nhận hàng",
    addNewAddress: "Thêm địa chỉ mới",
    editAddress: "Chỉnh sửa địa chỉ",
    onlyNumber: "Chỉ được nhập số",
    cityIsRequired: "Tỉnh/ Thành phố được yêu cầu",
    city: "Tỉnh/ Thành phố",
    district: "Quận/ Huyện",
    districtIsRequired: "Quận/ Huyện được yêu cầu",
    ward: "Phường/ Xã",
    wardIsRequired: "Phường/ Xã được yêu cầu",
    addressIsRequired: "Địa chỉ được yêu cầu",
    addressName: "Tên địa chỉ (Nhà riêng, cơ quan, ...)",
    back: "Trở lại",
    complete: "Hoàn tất",
    changeAddress: "Thay đổi địa chỉ",
    update: "Cập nhật",
    enterEmailToConfirmOrder: "Nhập Email để xác nhận đơn hàng",
    enterFullNameCheckout: "Nhập họ và tên của bạn",
    enterFullName: "Nhập họ và tên",
    enterPhoneNum: "Nhập số điện thoại liên hệ",
    nextStep: "Bước tiếp theo",
    easiestPayment: "Thanh toán dễ dàng và nhanh chóng nhất",
    fastPayment: "Thanh toán nhanh",
    notRequireCustomerLogIn: "Không yêu cầu đăng nhập đối với khách hàng",
    wrongCredential: "Tài khoản hoặc mật khẩu của bạn không đúng. Vui lòng thử lại",
    useOtherLoginMethod:
      "Đã có lỗi xảy ra, xin vui lòng thử lại hoặc dùng phương thức đăng ký khác.",
    shipFee: "Phí vận chuyển",
    order: "Đơn hàng",
    editShort: "Sửa",
    price: "Giá",
    warehouse: "kho hàng",
    provisionalPrice: "Tạm tính",
    discountCode: "Mã khuyến mãi",
    totalPrice: "Thành tiền",
    delivery: "Giao hàng",
    confirm: "Xác nhận",
    orderSuccess: "Đặt hàng thành công",
    yourOrderIdIs: "Mã đơn hàng của bạn là",
    youCanFollow:
      "Bạn có thể theo dõi thông tin về tình trạng đơn hàng cùng email xác nhận sẽ được gửi qua email của bạn.",
    youGoTo: "Bạn truy cập",
    orderManagement: "Quản lý đơn hàng",
    toFollowAndUpdate: "để theo dõi và cập nhật về tình trạng chi tiết của đơn hàng. Xin cảm ơn!",
    continueShopping: "Tiếp tục mua sắm",
    failOrder: "Đặt hàng không thành công",
    payOrder: "Thanh toán đơn hàng",
    byVNPayFail: "bằng thanh toán OnePAY không thành công",
    failTransaction: "Giao dịch không thành công.",
    contact: "Liên Hệ",
    retryInMins: "để biết thêm chi tiết. Bạn hãy thử thanh toán lại sau vài phút.",
    cart: "Giỏ hàng",
    proceedPayment: "Tiến hành thanh toán",
    raiseFundProcess: "Tiến trình gây quỹ",
    featureLowercase: "Nổi bật",
    latestNews: "Bản tin mới nhất",
    discoverLatest: "Khám phá những tin tức - xu hướng thị trường gần đây",
    topCategory: "Danh Mục Hàng Đầu",
    popularCategory: "Danh mục sản phấm được quan tâm nhiều nhất",
    whyChooseUs: "Tại sao chọn nhựa Long Thành",
    whyChooseUsContent:
      "Sản phẩm của Long Thành đều trải qua quy trình kiểm định nghiêm ngặt từ khâu thiết kế, sản xuất đến khâu hoàn thiện và giao hàng.",
    highPrice: "Giá cao",
    lowPrice: "Giá thấp",
    apply: "Áp dụng",
    featureTitle: "Đặc tính",
    FROM: "TỪ",
    TO: "ĐẾN",
    from: "Từ",
    above: "Trở lên",
    sorryNotFoundProducts: "Rất tiếc, không tìm thấy sản phẩm nào phù hợp với lựa chọn của bạn.",
    fromLowercase: "từ",
    toLowerCase: "đến",
    productList: "Danh sách sản phẩm",
    findv1: "Tìm kiếm",
    arrange: "Sắp xếp",
    resultFor: "Kết quả tìm kiếm cho",
    allProducts: "Tất cả sản phẩm",
    filter: "Bộ lọc",
    addressLowercase: "địa chỉ",
    add: "Thêm",
    cancel: "Huỷ bỏ",
    myAddress: "Địa chỉ của tôi",
    addNew: "Thêm mới",
    setAsDefault: "Đặt làm mặc định",
    delete: "Xoá",
    canceledOrder: "Đã hủy đơn hàng",
    cancelOrder: "Huỷ đơn hàng",
    cancelOrderConfirm: "Bạn có chắc muốn huỷ đơn hàng này?",
    content: "Nội dung",
    myOrder: "Đơn hàng của tôi",
    trackYourOrder: "Theo dõi trạng thái đơn hàng của bạn",
    enterOrderIDOrName: "Nhập mã đơn hoặc tên sản phẩm",
    orderDetail: "Chi tiết đơn hàng ",
    noti: "Thông báo",
    receiverAddress: "Địa chỉ người nhận",
    shippingMethod: "Hình thức giao hàng",
    freeShipping: "Nhựa Long Thành sẽ liên lạc đến bạn để báo giá vận chuyển",
    qty: "Số lượng",
    inventory: "Kho hàng",
    buyAgain: "Mua lại",
    buyMore: "Mua thêm",
    writeReview: "Viết nhận xét",
    trackOrder: "Theo dõi đơn hàng",
    total: "Tổng cộng",
    backToMyOrder: "Quay lại đơn hàng của tôi",
    orderId: "Mã đơn hàng",
    orderDate: "Ngày mua",
    money: "Số tiền",
    statusV2: "Trạng thái",
    viewDetail: "Xem chi tiết",
    sendReview: "Gửi đánh giá",
    yourThoughts: "Chia sẻ cảm nhận của bạn về sản phẩm nhé",
    favouriteProducts: "Sản phẩm yêu thích",
    yourFavouriteProducts: "Danh sách sản phẩm bạn đã yêu thích",
    deleteAll: "Xoá tất cả",
    myProfile: "Hồ sơ của tôi",
    secureProfile: "Quản lý thông tin hồ sơ để bảo mật tài khoản",
    changeAvatar: "Thay đổi ảnh đại diện",
    pickImage: "Chọn ảnh",
    pleaseEnterFullName: "Vui lòng nhập họ và tên",
    enterEmail: "Nhập email",
    enterPhoneNumv2: "Nhập số điện thoại",
    sex: "Giới tính",
    pleaseEnterSex: "Vui lòng chọn giới tính",
    male: "Nam",
    female: "Nữ",
    other: "Khác",
    birthday: "Ngày sinh",
    pleaseEnterBirthday: "Vui lòng nhập ngày sinh",
    connectAccount: "Liên kết tài khoản",
    orderStatus: "TRẠNG THÁI ĐƠN HÀNG",
    orderStatusDetail: "CHI TIẾT VỀ TRẠNG THÁI ĐƠN HÀNG",
    orderHas: "KIỆN HÀNG GỒM CÓ",
    backToOrderDetail: "Quay lại chi tiết đơn hàng",
    currentPassword: "Mật khẩu hiện tại",
    enterCurrentPassword: "Nhập mật khẩu hiện tại",
    newPassword: "Mật khẩu mới",
    reviewHistory: "Lịch sử đánh giá",
    reviewAndComment: "Lịch sử đánh giá và nhận xét các sản phẩm",
    recentlyView: "Sản phẩm đã xem",
    yourRecentlyView: "Danh sách sản phẩm bạn đã xem",
    reviews: "lượt",
    personalInfo: "Thông tin cá nhân",
    profile: "Hồ sơ",
    viewed: "Đã xem",
    relatedRecruitmentNews: "TIN TUYỂN DỤNG LIÊN QUAN",
    newsv1: "Tin tức",
    recruitment: "Tuyển dụng",
    recruitmentDetail: "Chi tiết tuyển dụng",
    recruitmentUppercase: "TUYỂN DỤNG",
    eventNewsSummary: "Tổng hợp tin tức về các sự kiện",
    notEnoughConditionUseDiscount: "Không đủ điều kiện sử dụng mã khuyến mãi",
    reduce: "Giảm",
    for: "cho",
    buyFrom: "khi mua từ",
    forOrderFrom: "cho đơn hàng từ",
    aboveText: "trở lên",
    overuseDiscountCode: "Hết luợt sử dụng mã khuyến mãi",
    cannotApplyDiscountCode: "Mã khuyến mãi không thể áp dụng",
    notDiscountCode: "Chưa có khuyến mãi nào",
    enterDiscountCode: "Nếu bạn có mã khuyến mãi, hãy nhập vào thanh bên trên",
    expire: "Hết hạn",
    limitedUse: "Giới hạn số lượng sử dụng",
    programName: "Tên chương trình",
    condition: "Điều kiện",
    discountv1: "Khuyến mãi",
    totalMoney: "Tổng tiền",
    placeOrder: "Đặt hàng",
    nowOnlyHasUpper: "Hiện chỉ còn",
    noProductInYourStore: "Không có sản phẩm nào trong cửa hàng của bạn",
    all: "Tất cả",
    openTime: "Giờ mở cửa",
    viewMap: "Xem bản đồ",
    image: "Hình ảnh",
    youCanFindStoreLocation: "Bạn có thể tìm cửa hàng theo vị trí gần nhất",
    sendLetter: "GỬI THƯ",
    inCityOverCountry: "tại các tỉnh/ thành phố trên toàn quốc",
    contactInfo: "Thông tin liên hệ",
    writeBelow: "Nhập nội dung bên dưới để kết nối ngay hôm nay!",
    validateEmailFail: "Xác nhận email thất bại",
    category: "Danh mục",
    callOnLowercase: "Kêu gọi",
    logInUppercase: "ĐĂNG NHẬP",
    reviewUp: "Đánh giá",
    updateFail: "Cập nhật thất bại",
    updatePersonalInfoFail: "Cập nhật thông tin cá nhân thất bại",
    updateSuccess: "Cập nhật thành công",
    pleaseChooseYour: "Chọn",
    titleEmailForgotIncorrect: "Email khôi phục không chính xác",
    desEmailForgotIncorrect: "Xin vui lòng nhập email mà bạn đã đăng ký",
    reviewInvalid: "Thêm đánh giá sản phẩm không thành công",
    reviewedProduct: "Đã đánh giá cho sản phẩm rồi",
    reasonCancelOrder: "Lý do hủy đơn hàng *",
    titleOrderIncorrect: "Đặt hàng không thành công",
    desOrderIncorrect: "Thông tin trong giỏ hàng đã có sự thay đổi",
    textBackToCart: "Trở về giỏ hàng",
    // contact form
    nameContact: "Họ và tên",
    phoneContact: "Số điện thoại",
    emailContact: "Email",
    contentContact: "Nội dung",
    textRequire: "được yêu cầu",
    nameExceedContact: "Họ và tên tối đa 50 ký tự",
    sendContactSuccess: "Gửi thư thành công",
    sendContactFail: "Gửi thư thất bại",
    requireEmailSocial:
      "Quý khách vui lòng cập nhật email vào thông tin facebook hoặc chọn tài khoản facebook khác",
    lockedAccountCheckout:
      "Tài khoản của bạn không còn tồn tại trên hệ thống vui lòng chọn Thanh toán nhanh để đặt hàng",
    textBackFastPayment: "Thanh toán nhanh",
    addToCartSuccess: "Sản phẩm được thêm vào giỏ hàng",
    exceedContentReview: "Xin quý khách vui lòng nhập đánh giá dưới 250 ký tự",
    "cau-hoi-thuong-gap": "cau-hoi-thuong-gap",
    "thong-tin-chinh-sach": "thong-tin-chinh-sach",
    "ve-long-thanh": "ve-long-thanh",
    "tuyen-dung": "tuyen-dung",
    "dieu-khoan-dich-vu": "dieu-khoan-dich-vu",
    "chinh-sach-bao-mat": "chinh-sach-bao-mat",
    cauHoiThuongGap: "Câu hỏi thường gặp",
    thongTinChinhSach: "Thông tin chính sách",
    veLongThanh: "Về long thành",
    tuyenDung: "Tuyển dụng",
    dieuKhoanDichVu: "Điều khoản dịch vụ",
    chinhSachBaoMat: "Chính sách bảo mật",
    "q-a": "cau-hoi-thuong-gap",
    privacy: "thong-tin-chinh-sach",
    "about-us": "ve-long-thanh",
    "category-product": "Danh mục sản phẩm",
    useTheFollowingKeywords: "Hoặc bạn có thể sử dụng từ khoá sau",
    pageNotFound: "Xin lỗi, trang bạn đang tìm kiếm không tồn tại!",
    or: "hoặc",
    account: "Tài khoản",
  },
  en: {
    storeSystem: "Shop System",
    language: "Language",
    customerSupport: "Customer Support",
    signUp: "Sign Up",
    logIn: "Log In",
    logOut: "Log Out",
    findPlaceholder: "Enter product's name",
    find: "Find",
    noProducts: "You don't have any products",
    subcriptionRegister: "Register for email subscription",
    subcriptionRegisterText: "Enter your email",
    subcriptionRegisterBtn: "REGISTER",
    emailIsRequired: "Email is required",
    emailIsInvalid: "Email is invalid",
    successSubscription: "Successful subscription",
    failSubscription: "Failed subscription. Please try again",
    existedEmail: "Email is already registered",
    address: "Address",
    email: "Email",
    hotline: "Hotline",
    aboutCompany: "About company",
    aboutLT: "About Long Thành",
    product: "Products",
    news: "News",
    FAQ: "FAQs",
    policy: "Policies",
    directLinks: "Direct Links",
    representativeOffice: "Representative Office",
    payment: "Check out",
    follow: "Follow",
    certification: "Certification",
    followOnFacebook: "Follow us on Facebook",
    followOnShopee: "Follow us on Shopee",
    followOnZalo: "Follow us on Zalo",
    homePage: "Home",
    relatedProducts: "Related Products",
    viewAll: "View All",
    allComboBelongsTo: "All combo belongs to",
    sortBy: "Sort By",
    priceContact: "Price",
    sorryCombo: "Sorry, can not find any combo",
    productReview: "Product Reviews",
    postedAt: "Posted at",
    detailDescription: "Detail description",
    viewMore: "View More",
    viewLess: "View Less",
    feature: "FEATURE",
    discount: "Discount",
    expireOn: "expire after",
    donate: "Donate",
    callOn: "CALL ON",
    status: "Status",
    inStock: "In Stock",
    outOfStock: "Out Of Stock",
    addToCart: "Add to cart",
    buy: "Buy",
    share: "Share",
    code: "Code",
    contactLongThanh: "Contact",
    chooseContactMethod: "Choose contact methods",
    review: "review",
    sold: "Sold",
    favourite: "Favourite",
    confirmEmail: "CONFIRM EMAIL",
    confirmEmailLowercase: "Confirm email",
    codeSent: "The verification code has been sent to",
    pleaseConfirm: "Please confirm.",
    validateEmail: "Validate email",
    agree: "Agree",
    createAccount: "Create Account",
    alreadyHaveAccount: "Already have an account?",
    fullName: "Fullname",
    fullNameRequired: "Fullname is required",
    fullNameExceed: "Fullname must be more than 10 characters long",
    phoneNum: "Phone number",
    phoneIsRequired: "Phone number is required",
    phoneIsInvalid: "Phone number is invalid",
    password: "Password",
    passwordIsRequired: "Password is required",
    passwordNotMatch: "Password does not match",
    confirmPassword: "Confirm password",
    byRegister: "By registering here, I agree with Long Thành Plastic about",
    termCondition: "Terms & conditions",
    privacyPolicy: "Privacy policy",
    orLoginWith: "or login with",
    dontHaveAccount: "Don't have account?",
    saveAccount: "Save account",
    forgotPassword: "Forgot password?",
    recoverPassword: "Please enter email to recover password",
    pleaseEnterEmail: "Please enter email",
    buyNow: "Buy now",
    nowOnlyHas: "now only has",
    items: "items",
    followLatestEmail: "Follow latest news via Email",
    yearAgo: "years ago",
    monthAgo: "months ago",
    dayAgo: "days ago",
    hourAgo: "hours ago",
    minAgo: "minutes ago",
    relatedPosts: "Related News",
    updatedSuccessfully: "Updated successfully",
    logInAgain: "Created account successfully. Please log in with new password.",
    logInNow: "Log in now",
    createNewPassword: "Create new password",
    enterNewPassword: "Enter new password",
    pleaseEnterPassword: "Please enter password",
    confirmNewPassword: "Confirm new password",
    confirmNewPasswordNotMatch: "Confirm password must be the same password",
    changePassword: "Change password",
    orderFail: "Place order failed",
    orderInfoChanged: "Your cart has been changed",
    backCart: "Return to cart",
    shippingInfo: "Shipping information",
    contactLater: "Contact later",
    paymentMethod: "Payment method",
    prevPage: "Previous",
    next: "Next",
    edit: "Edit",
    change: "Change",
    newAddress: "Add new address",
    newShippingAddress: "Add new shipping address",
    addNewAddress: "Add new address",
    editAddress: "Edit address",
    onlyNumber: "Enter only number",
    cityIsRequired: "City is required",
    city: "City",
    district: "District",
    districtIsRequired: "District is required",
    ward: "Ward",
    wardIsRequired: "Ward is required",
    addressIsRequired: "Address is required",
    addressName: "Address name (Home, Company, ...)",
    back: "Back",
    complete: "Complete",
    changeAddress: "Change address",
    update: "Update",
    enterEmailToConfirmOrder: "Enter Email to confirm order",
    enterFullNameCheckout: "Enter fullname",
    enterFullName: "Enter fullname",
    enterPhoneNum: "Enter phone number",
    nextStep: "Next step",
    easiestPayment: "Easiest and fatest payment",
    fastPayment: "Fast payment",
    notRequireCustomerLogIn: "Customers do not have to login",
    wrongCredential: "Username or password incorrect. Please try again",
    useOtherLoginMethod: "Something wrong, please try again or use other login method.",
    shipFee: "Shipping fee",
    order: "Order",
    editShort: "Edit",
    price: "Price",
    warehouse: "warehouse",
    provisionalPrice: "Provisional price",
    discountCode: "Discount code",
    totalPrice: "Total price",
    delivery: "Delivery",
    confirm: "Confirm",
    orderSuccess: "Place order successfully",
    yourOrderIdIs: "Your order ID is",
    youCanFollow: "You can track your order status by confirmation email sent to your email.",
    youGoTo: "You can go to",
    orderManagement: "Order management",
    toFollowAndUpdate: "to track and be updated about detail status of your order. Thank you!",
    continueShopping: "Continue shopping",
    failOrder: "Place order failed",
    payOrder: "Pay order",
    byVNPayFail: "by OnePAY payment unsuccessfully",
    failTransaction: "Unsuccessful transaction.",
    contact: "Contact",
    retryInMins: "to get detail. Please retry in some minutes.",
    cart: "Cart",
    proceedPayment: "Proceed payment",
    raiseFundProcess: "Raising fund process",
    featureLowercase: "Feature",
    latestNews: "Latest news",
    discoverLatest: "Discover news - market trends recently",
    topCategory: "Top Categories",
    popularCategory: "Popular Categories",
    whyChooseUs: "Why choose Long Thanh",
    whyChooseUsContent:
      "Long Thanh's products have undergone a rigorous testing process from design, production to finishing and delivery.",
    highPrice: "High price",
    lowPrice: "Low price",
    apply: "Apply",
    featureTitle: "Features",
    FROM: "FROM",
    TO: "TO",
    from: "From",
    above: "Above",
    sorryNotFoundProducts: "Sorry, we cannot find any products match your selection.",
    fromLowercase: "from",
    toLowerCase: "to",
    productList: "Product List",
    findv1: "Find",
    arrange: "Sort",
    resultFor: "Result for",
    allProducts: "All products",
    filter: "Filter",
    addressLowercase: "address",
    add: "Add",
    cancel: "Cancel",
    myAddress: "My address",
    addNew: "Add new",
    setAsDefault: "Set as default",
    delete: "Delete",
    canceledOrder: "Order canceled",
    cancelOrder: "Cancel order",
    cancelOrderConfirm: "Do you want to cancel this order?",
    content: "Content",
    myOrder: "My orders",
    trackYourOrder: "Track your orders",
    enterOrderIDOrName: "Enter order ID or products' name",
    orderDetail: "Order detail ",
    noti: "Notifications",
    receiverAddress: "Receiver's address",
    shippingMethod: "Shipping method",
    freeShipping: "Long Thanh Plastic will contact you for a shipping fee",
    qty: "Quantity",
    inventory: "Warehouse",
    buyAgain: "Buy again",
    buyMore: "Buy more",
    writeReview: "Write review",
    trackOrder: "Track order",
    total: "Total",
    backToMyOrder: "Return to my order",
    orderId: "Order number",
    orderDate: "Transaction date",
    money: "Price",
    statusV2: "Status",
    viewDetail: "View detail",
    sendReview: "Send review",
    yourThoughts: "Share your thoughts about products with us",
    favouriteProducts: "Favourite products",
    yourFavouriteProducts: "Your favourite products",
    deleteAll: "Delete all",
    myProfile: "My profile",
    secureProfile: "Manage profile information to secure your account",
    changeAvatar: "Change avatar",
    pickImage: "Upload image",
    pleaseEnterFullName: "Please enter fullname",
    enterEmail: "Enter email",
    enterPhoneNumv2: "Enter phone number",
    sex: "Gender",
    pleaseEnterSex: "Please choose gender",
    male: "Male",
    female: "Female",
    other: "Other",
    birthday: "Birthday",
    pleaseEnterBirthday: "Please enter your birthday",
    connectAccount: "Link account",
    orderStatus: "ORDER STATUS",
    orderStatusDetail: "ORDER STATUS DETAIL",
    orderHas: "ORDER HAS",
    backToOrderDetail: "Return to order detail",
    currentPassword: "Current password",
    enterCurrentPassword: "Enter your current password",
    newPassword: "New password",
    reviewHistory: "Review history",
    reviewAndComment: "Reviews and comments history of products",
    recentlyView: "Recently viewed products",
    yourRecentlyView: "Your recently viewed products",
    reviews: "reviews",
    personalInfo: "Personal information",
    profile: "Profile",
    viewed: "Viewed",
    relatedRecruitmentNews: "RELATED RECRUITMENT NEWS",
    newsv1: "News",
    recruitment: "Recruitment",
    recruitmentDetail: "Recruitment detail",
    recruitmentUppercase: "RECRUITMENT",
    eventNewsSummary: "News about events",
    notEnoughConditionUseDiscount: "Not enough conditions to use discount code",
    reduce: "Reduce",
    for: "for",
    buyFrom: "when buying from",
    forOrderFrom: "for order from",
    aboveText: "above",
    overuseDiscountCode: "Discount code usage expired",
    cannotApplyDiscountCode: "Cannot apply discount code",
    notDiscountCode: "No discount code",
    enterDiscountCode: "If you have discount code, enter on above bar",
    expire: "Expire",
    limitedUse: "Limited usage",
    programName: "Program name",
    condition: "Condition",
    discountv1: "Discount",
    totalMoney: "Total price",
    placeOrder: "Place order",
    nowOnlyHasUpper: "There are now only",
    noProductInYourStore: "No product in your store",
    all: "All",
    openTime: "Opening time",
    viewMap: "View map",
    image: "Image",
    youCanFindStoreLocation: "You can find nearest store",
    sendLetter: "SEND LETTER",
    inCityOverCountry: "in many cities over country",
    contactInfo: "Contact information",
    writeBelow: "Enter below content to get connected today!",
    validateEmailFail: "Confirm email failed",
    category: "Categories",
    callOnLowercase: "Call on",
    logInUppercase: "LOG IN",
    reviewUp: "Review",
    updateFail: "Update failed",
    updatePersonalInfoFail: "Update personal information failed",
    updateSuccess: "Update successfully",
    pleaseChooseYour: "Please choose your",
    titleEmailForgotIncorrect: "The recovery email is incorrect",
    desEmailForgotIncorrect: "Please enter your registered email address",
    reviewInvalid: "Add failed product review",
    reviewedProduct: "Already rated the product",
    reasonCancelOrder: "The reason for canceling the order *",
    titleOrderIncorrect: "Order failed",
    desOrderIncorrect: "The information in the shopping cart has changed",
    textBackToCart: "Back to cart",
    nameContact: "Full name",
    phoneContact: "Phone",
    emailContact: "Email",
    contentContact: "Content",
    textRequire: "required",
    nameExceedContact: "Full Name maximum 50 characters",
    sendContactSuccess: "Successful mailing",
    sendContactFail: "Failed mailing",
    requireEmailSocial:
      "Please update your email to your Facebook information or choose another facebook account",
    lockedAccountCheckout:
      "Your account no longer exists on the system, please select Quick payment to order",
    textBackFastPayment: "Fast payment",
    addToCartSuccess: "Product added to cart",
    exceedContentReview: "Please enter a review under 250 characters",
    "cau-hoi-thuong-gap": "q-a",
    "thong-tin-chinh-sach": "privacy",
    "ve-long-thanh": "about-us",
    "dieu-khoan-dich-vu": "dieu-khoan-dich-vu",
    "chinh-sach-bao-mat": "chinh-sach-bao-mat",
    cauHoiThuongGap: "Frequently asked questions",
    thongTinChinhSach: "Policy Information",
    veLongThanh: "About long thành",
    tuyenDung: "Recruit",
    dieuKhoanDichVu: "Terms of Service",
    chinhSachBaoMat: "Privacy Policy",
    "q-a": "cau-hoi-thuong-gap",
    privacy: "thong-tin-chinh-sach",
    "about-us": "ve-long-thanh",
    "category-product": "Product categories",
    useTheFollowingKeywords: "Or you can use the following keyword",
    pageNotFound: "This page could not be found",
    or: "or",
    account: "Account",
  },
};
