export const QUERY_KEYS = Object.freeze({
  CATEGORY_LIST: "CATEGORY_LIST",
  CATEGORY_ADD: "CATEGORY_ADD",
  CATEGORY_EDIT: "CATEGORY_EDIT",
  CATEGORY_DELETE: "CATEGORY_DELETE",
  CATEGORY_DELETE_SINGLE: "CATEGORY_DELETE_SINGLE",

  EMAIL_LIST: "EMAIL_LIST",
  EMAIL_DELETE: "EMAIL_DELETE",

  ARTICLE_LIST: "ARTICLE_LIST",
  ARTICLE_DELETE_MULTI: "ARTICLE_DELETE_MULTI",
  ARTICLE_CHECK_FULL_PUBLISHED: "ARTICLE_CHECK_FULL_PUBLISHED",

  QUIZ_GROUP_LIST: "QUIZ_GROUP_LIST",
  QUIZ_GROUP_ADD: "QUIZ_GROUP_ADD",
  QUIZ_GROUP_EDIT: "QUIZ_GROUP_EDIT",
  QUIZ_GROUP_DELETE: "QUIZ_GROUP_DELETE",

  QUIZ_LEVEL_LIST: "QUIZ_LEVEL_LIST",
  QUIZ_LEVEL_ADD: "QUIZ_LEVEL_ADD",
  QUIZ_LEVEL_EDIT: "QUIZ_LEVEL_EDIT",
  QUIZ_LEVEL_DELETE: "QUIZ_LEVEL_DELETE",

  QUIZ_DETAIL_ADD: "QUIZ_DETAIL_ADD",
  QUIZ_DETAIL_EDIT: "QUIZ_DETAIL_EDIT",
  QUIZ_DETAIL_DELETE: "QUIZ_DETAIL_DELETE",

  CBIS_LIST: "CBIS_LIST",
  CBIS_LIST_DELETE: "CBIS_LIST_DELETE",

  DOCUMENT_LIST: "DOCUMENT_LIST",
  USER_ACCOUNT_LIST: "USER_ACCOUNT_LIST",

  POLICY_LIST: "POLICY_LIST",
  GROUP_POLICY_LIST: "GROUP_POLICY_LIST",
  GROUP_POLICY_DETAIL: "GROUP_POLICY_DETAIL",

  SUBMITTED_ANSWER_LIST: "SUBMITTED_ANSWER_LIST",
  SUBMITTED_ANSWER_DETAIL: "SUBMITTED_ANSWER_DETAIL",
  SUBMITTED_ANSWER_ADD: "SUBMITTED_ANSWER_ADD",

  GET_LIST_CONFIG: "GET_LIST_CONFIG",
  GET_DETAIL_CONFIG: "GET_DETAIL_CONFIG",

  GET_LIST_ADMIN: " GET_LIST_ADMIN",
  GET_DETAIL_ADMIN: "GET_DETAIL_ADMIN",
});
